import * as esptooljs from 'https://unpkg.com/esptool-js@0.6.1/bundle.js';
(() => {
  'use strict';

  const $ = (id) => document.getElementById(id);
  const els = {
    supportWarning: $('supportWarning'), browserLabel: $('browserLabel'), toast: $('toast'), connectButton: $('connectButton'), connectButtonText: $('connectButtonText'), connectionPill: $('connectionPill'), connectionText: $('connectionText'), chipValue: $('chipValue'), revisionValue: $('revisionValue'), macValue: $('macValue'), flashValue: $('flashValue'), profileSelect: $('profileSelect'), dropZone: $('dropZone'), firmwareInput: $('firmwareInput'), browseButton: $('browseButton'), dropTitle: $('dropTitle'), fileDetails: $('fileDetails'), fileName: $('fileName'), fileMeta: $('fileMeta'), removeFileButton: $('removeFileButton'), flashAddress: $('flashAddress'), eraseButton: $('eraseButton'), flashButton: $('flashButton'), operationState: $('operationState'), progressMessage: $('progressMessage'), progressPercent: $('progressPercent'), progressBar: $('progressBar'), monitorState: $('monitorState'), baudSelect: $('baudSelect'), timestampToggle: $('timestampToggle'), pauseButton: $('pauseButton'), terminal: $('terminal'), serialInput: $('serialInput'), sendButton: $('sendButton'), clearButton: $('clearButton'), copyButton: $('copyButton'), resetButton: $('resetButton'), portValue: $('portValue'), bootloaderValue: $('bootloaderValue'), headerStatus: $('headerStatus'), headerStatusDot: $('headerStatusDot'), activeTarget: $('activeTarget'), emptyFlashState: $('emptyFlashState'), activeFlashState: $('activeFlashState'), transferredValue: $('transferredValue'), elapsedValue: $('elapsedValue'), progressStatus: $('progressStatus'), terminalLineCount: $('terminalLineCount'), activityLog: $('activityLog'), detailChip: $('detailChip'), detailRevision: $('detailRevision'), detailMac: $('detailMac'), detailFlash: $('detailFlash'), usbMode: $('usbMode'), emptyConnectButton: $('emptyConnectButton'), downloadLogButton: $('downloadLogButton'), settingsButton: $('settingsButton'), helpButton: $('helpButton'), modalBackdrop: $('modalBackdrop'), settingsModal: $('settingsModal'), helpModal: $('helpModal'), themeSelect: $('themeSelect'), defaultBaud: $('defaultBaud'), autoScrollToggle: $('autoScrollToggle'), confirmEraseToggle: $('confirmEraseToggle'), animationsToggle: $('animationsToggle')
  };
  const state = { port: null, transport: null, loader: null, firmware: null, busy: false, monitorReader: null, monitorActive: false, monitorPaused: true, monitorBuffer: '' };
  const hasSerial = 'serial' in navigator;

  function notify(message, kind = '') { els.toast.textContent = message; els.toast.className = `toast show ${kind}`; clearTimeout(notify.timer); notify.timer = setTimeout(() => { els.toast.className = 'toast'; }, 3600); }
  function log(message, kind = '') { const empty = els.terminal.querySelector('.terminal-empty'); if (empty) empty.remove(); const line = document.createElement('div'); line.className = `terminal-line ${kind ? `terminal-${kind}` : ''}`; const prefix = els.timestampToggle.checked ? `[${new Date().toLocaleTimeString([], { hour12: false })}] ` : ''; line.textContent = prefix + message; els.terminal.appendChild(line); if (els.terminalLineCount) els.terminalLineCount.textContent = `${els.terminal.querySelectorAll('.terminal-line').length} lines`; if (els.autoScrollToggle?.checked !== false) els.terminal.scrollTop = els.terminal.scrollHeight; }
  function clearLog() { els.terminal.innerHTML = ''; state.monitorBuffer = ''; if (els.terminalLineCount) els.terminalLineCount.textContent = '0 lines'; }
  function syncHeader(status, label) { if (!els.headerStatus) return; els.headerStatus.textContent = label; els.headerStatusDot?.parentElement?.classList.toggle('connected', status === 'connected'); }
  function syncDevicePanel() { if (!els.detailChip) return; els.detailChip.textContent = els.chipValue.textContent; els.detailRevision.textContent = els.revisionValue.textContent; els.detailMac.textContent = els.macValue.textContent; els.detailFlash.textContent = els.flashValue.textContent; els.usbMode.textContent = state.port ? 'Serial / USB' : 'Waiting for device'; }
  function syncFlashState() { const connected = Boolean(state.port); els.emptyFlashState?.classList.toggle('hidden', connected); els.activeFlashState?.classList.toggle('hidden', !connected); if (connected && els.activeTarget) els.activeTarget.textContent = chipText(); }
  function addActivity(message, kind = '') { if (!els.activityLog) return; const empty = els.activityLog.querySelector('.activity-empty'); if (empty) empty.remove(); const row = document.createElement('div'); row.className = `activity-entry ${kind}`; row.innerHTML = `<i></i><span>${message}</span><time>${new Date().toLocaleTimeString([], {hour:'2-digit', minute:'2-digit'})}</time>`; els.activityLog.prepend(row); while (els.activityLog.children.length > 5) els.activityLog.lastElementChild.remove(); }
  function setProgress(percent, message) { const safe = Math.max(0, Math.min(100, Math.round(percent))); els.progressBar.style.width = `${safe}%`; els.progressPercent.textContent = `${safe}%`; els.progressMessage.textContent = message; if (els.progressStatus) els.progressStatus.textContent = message.replace('…',''); }
  function setBusy(busy, label = 'WORKING') { state.busy = busy; [els.connectButton, els.eraseButton, els.flashButton, els.resetButton].forEach((button) => { button.disabled = busy; }); els.operationState.textContent = label; els.connectionPill.classList.toggle('busy', busy); }
  function setConnection(status, text) { els.connectionPill.className = `status-pill ${status}`; els.connectionText.textContent = text; }
  function formatBytes(bytes) { if (!bytes) return '0 B'; const units = ['B', 'KB', 'MB', 'GB']; const index = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1); return `${(bytes / (1024 ** index)).toFixed(index ? 2 : 0)} ${units[index]}`; }
  function errorMessage(error) { const message = error?.message || String(error); if (/cancel|abort/i.test(message)) return 'Port selection was cancelled. Choose the board in the browser picker to continue.'; if (/already open|in use|locked/i.test(message)) return 'The serial port is already in use. Close Arduino, PlatformIO, PuTTY, or another flasher and try again.'; if (/failed to connect|timeout|timed out|packet header|sync/i.test(message)) return 'Could not enter the ESP bootloader. Hold BOOT, tap RESET/EN, release both, then retry.'; if (/permission|denied|security/i.test(message)) return 'Serial permission was not granted. Choose the device again and allow browser access.'; if (/not found|unavailable|disconnect/i.test(message)) return 'The USB device is unavailable. Check the cable, driver, and connection, then retry.'; if (/invalid|binary|image/i.test(message)) return 'The firmware image could not be used. Confirm it is a valid .bin for this device.'; if (/erase/i.test(message)) return 'Flash erase failed. Re-enter bootloader mode and make sure the board stays connected.'; if (/write|flash|verify|md5/i.test(message)) return 'Firmware write or verification failed. Check the image address and USB connection, then retry.'; return 'The device operation failed. Check the connection and try again.'; }
  function terminalForLoader() { return { clean: () => {}, writeLine: (data) => log(String(data), 'info'), write: (data) => { state.monitorBuffer += String(data); const parts = state.monitorBuffer.split(/\r?\n/); state.monitorBuffer = parts.pop() || ''; parts.forEach((part) => part && log(part, 'info')); } }; }
  function ensureLibrary() { if (!esptooljs) throw new Error('esptool-js could not be loaded. Check your internet connection or CDN access.'); }
  async function createLoader() { ensureLibrary(); state.transport = new esptooljs.Transport(state.port, true); state.loader = new esptooljs.ESPLoader({ transport: state.transport, baudrate: 115200, terminal: terminalForLoader(), debugLogging: false }); setProgress(8, 'Connecting to bootloader…'); const chipName = await state.loader.main(); log(`Connected to ${chipName}.`, 'info'); return chipName; }
  async function releaseBootloader() { try { if (state.transport) await state.transport.disconnect(); } catch (_) {} state.transport = null; state.loader = null; }
  function chipText() { const chip = state.loader?.chip; return chip?.CHIP_NAME || state.loader?.chipName || 'ESP32'; }
  async function readChipDetails() {
    const chip = state.loader?.chip;
    els.chipValue.textContent = chipText(); syncDevicePanel();
    try { els.revisionValue.textContent = chip?.getChipRevision ? String(await chip.getChipRevision(state.loader)) : 'Detected'; } catch (_) { els.revisionValue.textContent = 'Detected'; }
    try { const mac = chip?.getMacAddr ? await chip.getMacAddr(state.loader) : null; els.macValue.textContent = mac ? (Array.isArray(mac) ? mac.map((part) => Number(part).toString(16).padStart(2, '0')).join(':').toUpperCase() : String(mac)) : 'Unavailable'; } catch (_) { els.macValue.textContent = 'Unavailable'; }
    try { const size = chip?.getFlashSize ? await chip.getFlashSize(state.loader) : null; els.flashValue.textContent = size ? `${size} MB` : 'Detected'; } catch (_) { els.flashValue.textContent = 'Detected'; }
  }
  async function connect() {
    if (!hasSerial) return notify('Web Serial is not available in this browser.', 'error');
    if (state.port) { await disconnect(); return; }
    try {
      ensureLibrary(); setBusy(true, 'CONNECTING'); setConnection('busy', 'CONNECTING'); els.connectButtonText.textContent = 'Connecting…'; log('Requesting a local serial port…', 'info');
      state.port = await navigator.serial.requestPort(); if (els.portValue) els.portValue.textContent = state.port.getInfo ? (state.port.getInfo().usbProductId ? `USB ${state.port.getInfo().usbProductId.toString(16).toUpperCase()}` : 'USB Serial') : 'USB Serial'; if (els.bootloaderValue) els.bootloaderValue.textContent = 'Connecting…'; const chipName = await createLoader(); await readChipDetails(); await state.loader.after('hard_reset'); await releaseBootloader(); if (els.bootloaderValue) els.bootloaderValue.textContent = 'Detected'; setProgress(100, 'Device ready'); setConnection('connected', 'CONNECTED'); syncHeader('connected', `${chipName} Connected`); syncFlashState(); addActivity(`Connected to ${chipName}`, 'success'); els.connectButtonText.textContent = 'Disconnect device'; notify(`${chipName} connected.`, 'success'); setBusy(false, 'READY');
      await startMonitor();
    } catch (error) { log(errorMessage(error), 'error'); notify(errorMessage(error), 'error'); addActivity(errorMessage(error), 'error'); await cleanupConnection(); setConnection('error', 'ERROR'); syncHeader('error', 'Connection error'); syncFlashState(); els.connectButtonText.textContent = 'Connect device'; setProgress(0, 'Waiting for a device and firmware'); setBusy(false, 'READY'); }
  }
  async function disconnect() { await stopMonitor(); await cleanupConnection(); setConnection('idle', 'DISCONNECTED'); syncHeader('idle', 'Disconnected'); syncFlashState(); if (els.portValue) els.portValue.textContent = 'Not selected'; if (els.bootloaderValue) els.bootloaderValue.textContent = '—'; syncDevicePanel(); els.connectButtonText.textContent = 'Connect device'; els.chipValue.textContent = '—'; els.revisionValue.textContent = '—'; els.macValue.textContent = '—'; els.flashValue.textContent = '—'; notify('Device disconnected.'); addActivity('Device disconnected'); }
  async function cleanupConnection() { try { if (state.transport) await state.transport.disconnect(); else if (state.port?.readable || state.port?.writable) await state.port.close(); } catch (_) {} state.transport = null; state.loader = null; state.port = null; }
  async function startMonitor() { if (!state.port || state.busy) return; try { await stopMonitor(); if (!state.port.readable) await state.port.open({ baudRate: Number(els.baudSelect.value) }); state.monitorActive = true; state.monitorPaused = false; els.pauseButton.textContent = 'PAUSE'; els.monitorState.classList.add('live'); els.monitorState.innerHTML = '<span class="status-dot"></span> LIVE'; readMonitor(); } catch (error) { log(`Monitor unavailable: ${errorMessage(error)}`, 'error'); } }
  async function readMonitor() { if (!state.port?.readable || !state.monitorActive) return; const reader = state.port.readable.getReader(); state.monitorReader = reader; const decoder = new TextDecoder(); try { while (state.monitorActive) { const { value, done } = await reader.read(); if (done) break; if (value && !state.monitorPaused) { const text = decoder.decode(value, { stream: true }); text.split(/\r?\n/).forEach((part) => { if (part) log(part); }); } } } catch (error) { if (state.monitorActive) log(`Serial read stopped: ${errorMessage(error)}`, 'error'); } finally { try { reader.releaseLock(); } catch (_) {} state.monitorReader = null; } }
  async function stopMonitor() { state.monitorActive = false; try { await state.monitorReader?.cancel(); } catch (_) {} state.monitorReader = null; if (els.monitorState) { els.monitorState.classList.remove('live'); els.monitorState.innerHTML = '<span class="status-dot"></span> PAUSED'; } els.pauseButton.textContent = 'RESUME'; }
  async function withLoader(action, label) { if (!state.port) return notify('Connect a device first.', 'error'); if (state.busy) return; try { setBusy(true, label.toUpperCase()); await stopMonitor(); if (!state.loader) await createLoader(); await action(); } catch (error) { log(errorMessage(error), 'error'); notify(errorMessage(error), 'error'); setConnection('error', 'ERROR'); } finally { await releaseBootloader(); setBusy(false, 'READY'); if (state.port) await startMonitor(); } }
  async function flash() { if (!state.firmware) return notify('Select a .bin firmware file first.', 'error'); let address; try { address = Number.parseInt(els.flashAddress.value.trim().replace(/^0x/i, ''), 16); if (!Number.isFinite(address) || address < 0) throw new Error('Flash address must be a hexadecimal value such as 0x0 or 0x1000.'); } catch (error) { return notify(error.message, 'error'); } await withLoader(async () => { setProgress(4, 'Preparing flash…'); const data = new Uint8Array(await state.firmware.arrayBuffer()); const options = { fileArray: [{ data, address }], flashMode: 'dio', flashFreq: '40m', flashSize: 'keep', eraseAll: false, compress: true, reportProgress: (_index, written, total) => { const percent = total ? (written / total) * 100 : 0; setProgress(percent, 'Writing firmware…'); if (els.transferredValue) els.transferredValue.textContent = `${formatBytes(written)} / ${formatBytes(total)}`; } }; log(`Writing ${state.firmware.name} at 0x${address.toString(16)}…`, 'info'); await state.loader.writeFlash(options); setProgress(100, 'Flash complete'); log('Flash complete. Resetting device…', 'info'); await state.loader.after('hard_reset'); notify('Firmware flashed successfully.', 'success'); addActivity('Firmware flash complete', 'success'); setConnection('connected', 'CONNECTED'); if (els.progressStatus) els.progressStatus.textContent = 'Complete'; }, 'flashing'); }
  async function erase() { if (els.confirmEraseToggle?.checked !== false && !window.confirm('Erase complete flash?\n\nThis will remove the existing firmware and stored data.')) return; await withLoader(async () => { setProgress(8, 'Erasing flash…'); log('Erasing complete flash memory…', 'info'); await state.loader.eraseFlash(); setProgress(100, 'Flash erased'); log('Flash erase complete.', 'info'); notify('Complete flash erase finished.', 'success'); addActivity('Complete flash erase finished', 'success'); }, 'erasing'); }
  async function reset() { await withLoader(async () => { log('Resetting device…', 'info'); if (state.loader?.after) await state.loader.after('hard_reset'); else if (state.port) { await state.port.setSignals({ dataTerminalReady: false, requestToSend: true }); await new Promise((resolve) => setTimeout(resolve, 100)); await state.port.setSignals({ dataTerminalReady: false, requestToSend: false }); } notify('Reset signal sent.', 'success'); addActivity('Reset signal sent', 'success'); }, 'resetting'); }
  function setFirmware(file) { if (!file) return; if (!file.name.toLowerCase().endsWith('.bin')) return notify('Please choose a .bin firmware file.', 'error'); state.firmware = file; els.dropTitle.textContent = 'Firmware selected'; els.fileDetails.classList.remove('hidden'); els.fileName.textContent = file.name; els.fileMeta.textContent = `${formatBytes(file.size)} · local only · ${els.profileSelect.options[els.profileSelect.selectedIndex].text}`; notify(`${file.name} ready to flash.`, 'success'); }
  async function sendSerial() { const text = els.serialInput.value; if (!text || !state.port?.writable) return notify('Connect a device before sending serial data.', 'error'); try { const writer = state.port.writable.getWriter(); await writer.write(new TextEncoder().encode(`${text}\r\n`)); writer.releaseLock(); log(`> ${text}`, 'info'); els.serialInput.value = ''; } catch (error) { notify(`Send failed: ${errorMessage(error)}`, 'error'); } }

  if (els.browserLabel) els.browserLabel.textContent = hasSerial ? 'WEB SERIAL READY' : 'WEB SERIAL UNAVAILABLE';
  if (!hasSerial) els.supportWarning.classList.remove('hidden');
  els.connectButton.addEventListener('click', connect); els.flashButton.addEventListener('click', flash); els.eraseButton.addEventListener('click', erase); els.resetButton.addEventListener('click', reset); els.browseButton.addEventListener('click', () => els.firmwareInput.click()); els.dropZone.addEventListener('click', (event) => { if (event.target !== els.browseButton) els.firmwareInput.click(); }); els.dropZone.addEventListener('keydown', (event) => { if (event.key === 'Enter' || event.key === ' ') els.firmwareInput.click(); }); els.firmwareInput.addEventListener('change', () => setFirmware(els.firmwareInput.files?.[0])); els.removeFileButton.addEventListener('click', () => { state.firmware = null; els.firmwareInput.value = ''; els.fileDetails.classList.add('hidden'); els.dropTitle.textContent = 'Drop your .bin here'; }); ['dragenter', 'dragover'].forEach((eventName) => els.dropZone.addEventListener(eventName, (event) => { event.preventDefault(); els.dropZone.classList.add('dragging'); })); ['dragleave', 'drop'].forEach((eventName) => els.dropZone.addEventListener(eventName, (event) => { event.preventDefault(); els.dropZone.classList.remove('dragging'); })); els.dropZone.addEventListener('drop', (event) => setFirmware(event.dataTransfer.files?.[0])); els.clearButton.addEventListener('click', clearLog); els.copyButton.addEventListener('click', async () => { try { await navigator.clipboard.writeText(els.terminal.innerText); notify('Serial output copied.', 'success'); } catch (_) { notify('Clipboard access was unavailable.', 'error'); } }); els.sendButton.addEventListener('click', sendSerial); els.serialInput.addEventListener('keydown', (event) => { if (event.key === 'Enter') sendSerial(); }); els.pauseButton.addEventListener('click', () => { state.monitorPaused = !state.monitorPaused; els.pauseButton.textContent = state.monitorPaused ? 'RESUME' : 'PAUSE'; els.monitorState.classList.toggle('live', !state.monitorPaused); els.monitorState.innerHTML = `<span class="status-dot"></span> ${state.monitorPaused ? 'PAUSED' : 'LIVE'}`; }); els.baudSelect.addEventListener('change', async () => { if (state.port && !state.busy) { await stopMonitor(); try { if (state.port.readable || state.port.writable) await state.port.close(); await startMonitor(); } catch (error) { notify(`Baud change failed: ${errorMessage(error)}`, 'error'); } } }); els.downloadLogButton?.addEventListener('click', () => { const blob = new Blob([els.terminal.innerText], {type:'text/plain'}); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'esp32-flash-lab.log'; link.click(); URL.revokeObjectURL(url); }); els.emptyConnectButton?.addEventListener('click', connect);
  function openModal(which) { els.modalBackdrop?.classList.remove('hidden'); els.settingsModal?.classList.toggle('hidden', which !== 'settings'); els.helpModal?.classList.toggle('hidden', which !== 'help'); } function closeModal() { els.modalBackdrop?.classList.add('hidden'); } els.settingsButton?.addEventListener('click', () => openModal('settings')); els.helpButton?.addEventListener('click', () => openModal('help')); els.modalBackdrop?.addEventListener('click', (event) => { if (event.target === els.modalBackdrop || event.target.closest('[data-close-modal]')) closeModal(); });
  const prefKey = 'esp32-flash-lab-preferences'; let prefs = {}; try { prefs = JSON.parse(localStorage.getItem(prefKey) || '{}'); } catch (_) {} if (prefs.baud) { els.baudSelect.value = String(prefs.baud); els.defaultBaud.value = String(prefs.baud); } if (prefs.timestamp !== undefined) els.timestampToggle.checked = prefs.timestamp; if (prefs.autoScroll !== undefined) els.autoScrollToggle.checked = prefs.autoScroll; if (prefs.confirmErase !== undefined) els.confirmEraseToggle.checked = prefs.confirmErase; if (prefs.animations === false) { els.animationsToggle.checked = false; document.documentElement.style.setProperty('--ease','linear'); } els.defaultBaud?.addEventListener('change', () => { els.baudSelect.value = els.defaultBaud.value; localStorage.setItem(prefKey, JSON.stringify({...prefs, baud: els.defaultBaud.value})); }); els.timestampToggle.addEventListener('change', () => localStorage.setItem(prefKey, JSON.stringify({...prefs, timestamp: els.timestampToggle.checked}))); els.autoScrollToggle?.addEventListener('change', () => localStorage.setItem(prefKey, JSON.stringify({...prefs, autoScroll: els.autoScrollToggle.checked}))); els.confirmEraseToggle?.addEventListener('change', () => localStorage.setItem(prefKey, JSON.stringify({...prefs, confirmErase: els.confirmEraseToggle.checked}))); els.animationsToggle?.addEventListener('change', () => { localStorage.setItem(prefKey, JSON.stringify({...prefs, animations: els.animationsToggle.checked})); document.documentElement.style.setProperty('--ease', els.animationsToggle.checked ? 'cubic-bezier(.23,1,.32,1)' : 'linear'); }); els.themeSelect?.addEventListener('change', () => { document.documentElement.dataset.theme = els.themeSelect.value; localStorage.setItem(prefKey, JSON.stringify({...prefs, theme: els.themeSelect.value})); }); if (prefs.theme) els.themeSelect.value = prefs.theme;
  els.profileSelect.addEventListener('change', () => { if (state.firmware) els.fileMeta.textContent = `${formatBytes(state.firmware.size)} · local only · ${els.profileSelect.options[els.profileSelect.selectedIndex].text}`; }); if (hasSerial) navigator.serial.addEventListener('disconnect', (event) => { if (state.port === event.port) { cleanupConnection(); setConnection('error', 'DISCONNECTED'); syncHeader('error', 'Device disconnected'); syncFlashState(); addActivity('Device disconnected', 'error'); els.connectButtonText.textContent = 'Connect device'; log('Device disconnected.', 'error'); notify('The serial device was disconnected.', 'error'); } });
})();
